name: mobile
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.4.0
  intl: any
  flutter_dotenv: any
  image_picker: any
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  path_provider: ^2.0.15
  pdf: ^3.10.4
  printing: ^5.11.0
  charts_flutter_new: ^0.12.0 
  share_plus: ^11.0.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  generate: true
