name: mobile
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  intl: any
  flutter_dotenv: any
  image_picker: any
  shared_preferences: any
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  http: ^0.13.6
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  generate: true
